exports.config =
	baseUrl: ""
	timeSpeedFactor: 1
	roundingDecimals: 5
	# Animations
	animationPrecision: 60
	animationDebug: false
	animationProfile: false
	defaultViewWidth: 100
	defaultViewHeight: 100
	defaultViewBackgroundColor: "rgba(0,150,200,0.5)"